FROM php:7.0-apache

RUN mkdir /var/www/html/close
RUN mkdir /var/www/html/close/closer
RUN mkdir /var/www/html/close/closer/on-fire
RUN mkdir /var/www/html/close/closer/on-fire/volcanic

COPY index.html /var/www/html
COPY Forest.html /var/www/html/close
COPY Desert.html /var/www/html/close
COPY City.html /var/www/html/close/closer
COPY Motel.html /var/www/html/close/closer/on-fire
COPY script.js /var/www/html/close/closer/on-fire/volcanic
COPY 66h6ch61h67h.html /var/www/html/close/closer/on-fire/volcanic
