FROM php:7.0-apache

COPY index.html /var/www/html
COPY Forest.html /var/www/html/close
COPY Desert.html /var/www/html/close
COPY script.js /var/www/html/close/closer/on-fire/volcanic/
COPY 66h6ch61h67h.html /var/www/html/close/closer/on-fire/volcanic/
